### ISSUE TITLE
Identifier

### ISSUE THREAD

**Issue by mybigman** [moltin/cart#10]
Hi,

Just wondering if you could provide some more information on access the $identifier.

Cart::has($itemIdentifier);
Cart::item($itemIdentifier);
Cart::remove($itemIdentifier);

What I'm not getting is how am I suppose the know the $identifier when all I know is the item id.

Could you please provide some sample uses.

Many thanks.

**Comment by judgej** [comment]
As always, use-case is the bitch. I have a need to check if a product is in the cart or not, because I have products that can only be purchased once and once only. Creating a `hasId()` method that checks the `id` of each item rather than the `identifier` of each item, does the trick.
