### ISSUE TITLE
Accessing the Cart throughout application

### ISSUE THREAD

**Issue by dcolumbus** [moltin/cart#5]
This isn't really an "issue" per-say, but I do think it should be outlined in your documentation... 

What is the best way to reference the cart throughout an application? For example, in Laravel, if I want to pull up the Cart within a Route, what's the recommended way of getting the Cart object?

Have you thought about adding a static method? Check out Cartify: https://github.com/brunogaspar/cartify

Cartify::cart()->total_items() is an example of how the static methods can be called from anywhere in the app.

**Comment by lesfleurs** [comment]
does anyone know how this would work for codeigniter?
